//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrontEnd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrontEnd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Domain.FrontEnd", typeof(FrontEnd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Requests.
        /// </summary>
        internal static string Absence_Requests {
            get {
                return ResourceManager.GetString("Absence Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absences.
        /// </summary>
        internal static string Absences {
            get {
                return ResourceManager.GetString("Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users to ask.
        /// </summary>
        internal static string Add_users_to_ask {
            get {
                return ResourceManager.GetString("Add users to ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        internal static string Additional_info {
            get {
                return ResourceManager.GetString("Additional info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Users.
        /// </summary>
        internal static string App_Users {
            get {
                return ResourceManager.GetString("App Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete team?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_team_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete team?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this department?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_department_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this department?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this meeting?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_meeting_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this meeting?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this message?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_message_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this message?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this person?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_person_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this person?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user in team?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_user_in_team_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this user in team?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to.
        /// </summary>
        internal static string Assign_to {
            get {
                return ResourceManager.GetString("Assign to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Department.
        /// </summary>
        internal static string Create_a_new_Department {
            get {
                return ResourceManager.GetString("Create a new Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Meeting.
        /// </summary>
        internal static string Create_a_new_Meeting {
            get {
                return ResourceManager.GetString("Create a new Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Task.
        /// </summary>
        internal static string Create_a_new_Task {
            get {
                return ResourceManager.GetString("Create a new Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Ticket.
        /// </summary>
        internal static string Create_a_Ticket {
            get {
                return ResourceManager.GetString("Create a Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string Create_Account {
            get {
                return ResourceManager.GetString("Create Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Person.
        /// </summary>
        internal static string Create_new_Person {
            get {
                return ResourceManager.GetString("Create new Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Team.
        /// </summary>
        internal static string Create_new_Team {
            get {
                return ResourceManager.GetString("Create new Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person in Team.
        /// </summary>
        internal static string Create_Person_in_Team {
            get {
                return ResourceManager.GetString("Create Person in Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there are no departments!.
        /// </summary>
        internal static string Currently_there_are_no_departments_ {
            get {
                return ResourceManager.GetString("Currently there are no departments!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there are no teams!.
        /// </summary>
        internal static string Currently_there_are_no_teams_ {
            get {
                return ResourceManager.GetString("Currently there are no teams!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there are no users in teams!.
        /// </summary>
        internal static string Currently_there_are_no_users_in_teams_ {
            get {
                return ResourceManager.GetString("Currently there are no users in teams!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Department.
        /// </summary>
        internal static string Delete_Department {
            get {
                return ResourceManager.GetString("Delete Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Meeting.
        /// </summary>
        internal static string Delete_Meeting {
            get {
                return ResourceManager.GetString("Delete Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Message.
        /// </summary>
        internal static string Delete_Message {
            get {
                return ResourceManager.GetString("Delete Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person.
        /// </summary>
        internal static string Delete_Person {
            get {
                return ResourceManager.GetString("Delete Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Team.
        /// </summary>
        internal static string Delete_Team {
            get {
                return ResourceManager.GetString("Delete Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User in Team.
        /// </summary>
        internal static string Delete_User_in_Team {
            get {
                return ResourceManager.GetString("Delete User in Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        internal static string Department_Name {
            get {
                return ResourceManager.GetString("Department Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Department.
        /// </summary>
        internal static string Edit_Department {
            get {
                return ResourceManager.GetString("Edit Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meeting.
        /// </summary>
        internal static string Edit_Meeting {
            get {
                return ResourceManager.GetString("Edit Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Person.
        /// </summary>
        internal static string Edit_Person {
            get {
                return ResourceManager.GetString("Edit Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Person in Team.
        /// </summary>
        internal static string Edit_Person_in_Team {
            get {
                return ResourceManager.GetString("Edit Person in Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Team.
        /// </summary>
        internal static string Edit_Team {
            get {
                return ResourceManager.GetString("Edit Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string End_Date {
            get {
                return ResourceManager.GetString("End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the team since.
        /// </summary>
        internal static string In_the_team_since {
            get {
                return ResourceManager.GetString("In the team since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the team until.
        /// </summary>
        internal static string In_the_team_until {
            get {
                return ResourceManager.GetString("In the team until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mandatory.
        /// </summary>
        internal static string Is_Mandatory {
            get {
                return ResourceManager.GetString("Is Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Absence Request.
        /// </summary>
        internal static string Manage_Absence_Request {
            get {
                return ResourceManager.GetString("Manage Absence Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Absences/Tickets.
        /// </summary>
        internal static string Manage_Absences_Tickets {
            get {
                return ResourceManager.GetString("Manage Absences/Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Meetings.
        /// </summary>
        internal static string Manage_Meetings {
            get {
                return ResourceManager.GetString("Manage Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Task.
        /// </summary>
        internal static string Manage_Task {
            get {
                return ResourceManager.GetString("Manage Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tasks.
        /// </summary>
        internal static string Manage_Tasks {
            get {
                return ResourceManager.GetString("Manage Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string Manage_users {
            get {
                return ResourceManager.GetString("Manage users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message content.
        /// </summary>
        internal static string Message_content {
            get {
                return ResourceManager.GetString("Message content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Absences.
        /// </summary>
        internal static string My_Absences {
            get {
                return ResourceManager.GetString("My Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string My_Account {
            get {
                return ResourceManager.GetString("My Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Career.
        /// </summary>
        internal static string My_Career {
            get {
                return ResourceManager.GetString("My Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Messages.
        /// </summary>
        internal static string My_Messages {
            get {
                return ResourceManager.GetString("My Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        internal static string My_Tasks {
            get {
                return ResourceManager.GetString("My Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Teams.
        /// </summary>
        internal static string My_Teams {
            get {
                return ResourceManager.GetString("My Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tickets.
        /// </summary>
        internal static string My_Tickets {
            get {
                return ResourceManager.GetString("My Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No absences have been requested!.
        /// </summary>
        internal static string No_absences_have_been_requested_ {
            get {
                return ResourceManager.GetString("No absences have been requested!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meetings are upcoming!.
        /// </summary>
        internal static string No_meetings_are_upcoming_ {
            get {
                return ResourceManager.GetString("No meetings are upcoming!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks remaining!.
        /// </summary>
        internal static string No_tasks_remaining_ {
            get {
                return ResourceManager.GetString("No tasks remaining!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No teams.
        /// </summary>
        internal static string No_teams {
            get {
                return ResourceManager.GetString("No teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tickets have been sent to you!.
        /// </summary>
        internal static string No_tickets_have_been_sent_to_you_ {
            get {
                return ResourceManager.GetString("No tickets have been sent to you!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons In Teams.
        /// </summary>
        internal static string Persons_In_Teams {
            get {
                return ResourceManager.GetString("Persons In Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasoning.
        /// </summary>
        internal static string Reasoning {
            get {
                return ResourceManager.GetString("Reasoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registred successfully. Please wait for the admin to verify your account! :).
        /// </summary>
        internal static string Registred_successfully {
            get {
                return ResourceManager.GetString("Registred successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Absence.
        /// </summary>
        internal static string Request_a_absence {
            get {
                return ResourceManager.GetString("Request a absence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required!.
        /// </summary>
        internal static string Required_ {
            get {
                return ResourceManager.GetString("Required!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Department.
        /// </summary>
        internal static string Select_a_department {
            get {
                return ResourceManager.GetString("Select a department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a member.
        /// </summary>
        internal static string Select_a_member {
            get {
                return ResourceManager.GetString("Select a member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Team.
        /// </summary>
        internal static string Select_Team {
            get {
                return ResourceManager.GetString("Select Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Team Role.
        /// </summary>
        internal static string Select_Team_Role {
            get {
                return ResourceManager.GetString("Select Team Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a User.
        /// </summary>
        internal static string Select_User {
            get {
                return ResourceManager.GetString("Select User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a new message.
        /// </summary>
        internal static string Send_a_new_message {
            get {
                return ResourceManager.GetString("Send a new message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to.
        /// </summary>
        internal static string Send_to {
            get {
                return ResourceManager.GetString("Send to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        internal static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Start_Date {
            get {
                return ResourceManager.GetString("Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts.
        /// </summary>
        internal static string Starts {
            get {
                return ResourceManager.GetString("Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Leader.
        /// </summary>
        internal static string Team_Leader {
            get {
                return ResourceManager.GetString("Team Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Management.
        /// </summary>
        internal static string Team_Management {
            get {
                return ResourceManager.GetString("Team Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team member.
        /// </summary>
        internal static string Team_member {
            get {
                return ResourceManager.GetString("Team member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        internal static string Team_Members {
            get {
                return ResourceManager.GetString("Team Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        internal static string Team_Name {
            get {
                return ResourceManager.GetString("Team Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Role.
        /// </summary>
        internal static string Team_Role {
            get {
                return ResourceManager.GetString("Team Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Role Name.
        /// </summary>
        internal static string Team_Role_Name {
            get {
                return ResourceManager.GetString("Team Role Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text message.
        /// </summary>
        internal static string Text_message {
            get {
                return ResourceManager.GetString("Text message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required!.
        /// </summary>
        internal static string This_field_is_required_ {
            get {
                return ResourceManager.GetString("This field is required!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets/Absences.
        /// </summary>
        internal static string Tickets_Absences {
            get {
                return ResourceManager.GetString("Tickets/Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Meetings.
        /// </summary>
        internal static string Upcoming_Meetings {
            get {
                return ResourceManager.GetString("Upcoming Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        internal static string Update_Status {
            get {
                return ResourceManager.GetString("Update Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status for.
        /// </summary>
        internal static string Update_Status_for {
            get {
                return ResourceManager.GetString("Update Status for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string User_Management {
            get {
                return ResourceManager.GetString("User Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Ticket.
        /// </summary>
        internal static string Write_a_ticket {
            get {
                return ResourceManager.GetString("Write a ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in any teams!.
        /// </summary>
        internal static string You_are_not_in_any_teams_ {
            get {
                return ResourceManager.GetString("You are not in any teams!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the only member!.
        /// </summary>
        internal static string You_are_the_only_member_ {
            get {
                return ResourceManager.GetString("You are the only member!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have/haven&apos;t sent any messages!.
        /// </summary>
        internal static string You_dont_have_havent_sent_any_messages_ {
            get {
                return ResourceManager.GetString("You dont have/havent sent any messages!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t requested any absences!
        ///.
        /// </summary>
        internal static string You_havent_requested_any_absences_ {
            get {
                return ResourceManager.GetString("You havent requested any absences!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t written any tickets!.
        /// </summary>
        internal static string You_havent_written_any_tickets_ {
            get {
                return ResourceManager.GetString("You havent written any tickets!", resourceCulture);
            }
        }
    }
}
