version: '3.8'

services:
  db:
    image: postgres:16
    container_name: collabcore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collabcorebase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    build: .
    container_name: collabcore-webapp
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=collabcorebase;Username=postgres;Password=postgres
    ports:
      - "5000:8888"
    networks:
      - default

volumes:
  pgdata:
    
networks:
  default:
    external:
      name: collabcore-network
