version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: exam-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exambase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
